[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "November"
day = "6"
year = "2022"
time = "11:43"
am_pm = "PM"
instant = 0

[client_manager]
filename = ""
