[message_center]
message = "Test of message center\n"
possible_dates = [ "master_list_1.csv", "master_list_2.csv", "tegan.csv", "chris 102422.csv", "tegan 02122022.csv", "test-message.csv",]
final_dates = []
master_select = "on"
client_select = "on"
month = "November"
day = "10"
year = "2022"
time = "11:05"
am_pm = "PM"
instant = 1

[client_manager]
filename = "tegan.csv"
