[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "March"
day = "5"
year = "2023"
time = "10:18"
am_pm = "PM"
instant = 1

[client_manager]
filename = "test 03052023.csv"
