[message_center]
message = "Hello World\n\n\n\n\n\n\n\n\n\n\n\n\n"
possible_dates = [ "master_list_2.csv", "chris 102422.csv", "test-message.csv",]
final_dates = [ "master_list_1.csv",]
master_select = "on"
client_select = "on"
month = "November"
day = "6"
year = "2022"
time = "12:52"
am_pm = "AM"
instant = 1

[client_manager]
filename = "test-message.csv"
