[message_center]
message = "Test of message center\n"
possible_dates = [ "master_list_1.csv", "master_list_2.csv", "chris 102422.csv",]
final_dates = [ "test-message.csv",]
master_select = "on"
client_select = "on"
month = "November"
day = "10"
year = "2022"
time = "11:05"
am_pm = "PM"
instant = 1

[client_manager]
filename = "test-message.csv"
