[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "November"
day = "8"
year = "2022"
time = "01:28"
am_pm = "AM"
instant = 0

[client_manager]
filename = ""
