[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "February"
day = "2"
year = "2023"
time = "9:59"
am_pm = "PM"
instant = 0

[client_manager]
filename = ""
