[message_center]
message = "Test of message center\n"
possible_dates = [ "tegan.csv", "tyler.csv", "test 12072022.csv", "tyler 102422.csv",]
final_dates = [ "tegan 02132023.csv",]
master_select = "on"
client_select = "on"
month = "December"
day = "7"
year = "2022"
time = "08:51"
am_pm = "PM"
instant = 1

[client_manager]
filename = "tegan.csv"
