[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "December"
day = "8"
year = "2022"
time = "11:16"
am_pm = "PM"
instant = 1

[client_manager]
filename = ""
