[message_center]
message = "\n"
possible_dates = []
final_dates = []
master_select = "off"
client_select = "off"
month = "January"
day = "17"
year = "2023"
time = "11:45"
am_pm = "PM"
instant = 1

[client_manager]
filename = ""
